name: bundle

on: [push]

jobs:
  grunt-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile with Grunt
      uses: elstudio/actions-js-build/build@v4
      with:
        args: "bundle"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: docs.techne.net UI bundle
        # A file, directory or wildcard pattern that describes what to upload
        path: build/ui-bundle.zip